version: '3'

tasks:
  test-all:
    desc: Run all tests
    cmds:
      - task: test-echo
      - task: test-uniqueids
      - task: test-broadcast
      - task: test-counter
      - task: test-kafka

  test-echo:
    desc: Run echo test
    cmds:
      - go test ./echo

  test-uniqueids:
    desc: Run uniqueids test
    cmds:
      - go test ./uniqueids

  test-broadcast:
    desc: Run broadcast test
    cmds:
      - go test ./broadcast

  test-counter:
    desc: Run counter test
    cmds:
      - go test ./counter

  test-kafka:
    desc: Run kafka test
    cmds:
      - go test ./kafka

  run-all:
    desc: Run all
    cmds:
      - task: run-echo
      - task: run-unique-ids
      - task: run-broadcast
      - task: run-counter
      - task: run-kafka

  run-echo:
    desc: Run echo test
    cmds:
      - task: build-echo
      - maelstrom test -w echo --bin ./build/echo --node-count 1 --time-limit 10

  run-uniqueids:
    desc: Run uniqueids test
    cmds:
      - task: build-uniqueids
      - maelstrom test -w unique-ids --bin ./build/uniqueids --time-limit 30 --rate 1000 --node-count 3 --availability total --nemesis partition

  run-broadcast:
    desc: Run broadcast test
    cmds:
      - task: run-broadcast-single
      - task: run-broadcast-multi
      - task: run-broadcast-fault-tolerant
      - task: run-broadcast-efficient

  run-broadcast-single:
    desc: Run broadcast single test
    cmds:
      - task: build-broadcast
      - maelstrom test -w broadcast --bin ./build/broadcast --node-count 1 --time-limit 20 --rate 10

  run-broadcast-multi:
    desc: Run broadcast multi-node test
    cmds:
      - task: build-broadcast
      - maelstrom test -w broadcast --bin ./build/broadcast --node-count 5 --time-limit 20 --rate 10

  run-broadcast-fault-tolerant:
    desc: Run broadcast fault-tolerant test
    cmds:
      - task: build-broadcast
      - maelstrom test -w broadcast --bin ./build/broadcast --node-count 5 --time-limit 20 --rate 10 --nemesis partition

  run-broadcast-efficient:
    desc: Run broadcast efficient test
    cmds:
      - task: build-broadcast
      - maelstrom test -w broadcast --bin ./build/broadcast --node-count 25 --time-limit 20 --rate 100 --latency 100

  run-counter:
    desc: Run counter test
    cmds:
      - task: build-counter
      - maelstrom test -w g-counter --bin ./build/counter --node-count 3 --rate 100 --time-limit 20 --nemesis partition

  run-kafka:
    desc: Run kafka test
    cmds:
      - task: build-kafka
      - maelstrom test -w kafka --bin ./build/kafka --node-count 1 --concurrency 2n --time-limit 20 --rate 1000

  build-all:
    desc: Build all
    cmds:
      - task: build-echo
      - task: build-uniqueids
      - task: build-broadcast
      - task: build-counter
      - task: build-kafka

  build-echo:
    desc: Build echo test
    sources:
      - echo/**/*
    generates:
      - build/echo
    cmds:
      - go build -o ./build ./echo

  build-uniqueids:
    desc: Build uniqueids test
    sources:
      - uniqueids/**/*
    generates:
      - build/uniqueids
    cmds:
      - go build -o ./build ./uniqueids

  build-broadcast:
    desc: Build broadcast test
    sources:
      - broadcast/**/*
    generates:
      - build/broadcast
    cmds:
      - go build -o ./build ./broadcast

  build-counter:
    desc: Build counter test
    sources:
      - counter/**/*
    generates:
      - build/counter
    cmds:
      - go build -o ./build ./counter

  build-kafka:
    desc: Build kafka test
    sources:
      - kafka/**/*
    generates:
      - build/kafka
    cmds:
      - go build -o ./build ./kafka
